### PR TITLE
Support cmp's custom completion menu

### PR DESCRIPTION
**Pull request by uga-rosa**
The cmp completion menu was created by hrsh7th, so you will need a special way to close it.

### CODE REVIEW

**Comment by uga-rosa** [comment]
I have used pcall to automatically determine this, but I think I can also explicitly state that cmp is used in setup. Which would be better?

**Comment by uga-rosa** [comment]
Not only in cmp, but also in signature.nvim, etc., floatingwindow residuals occur, so it may be better to fire the autocmd for InsertLeave.

**Comment by dcampos** [comment]
Thanks for looking into this. Your code looks good as it is, but as you commented, I'm afraid other workarounds will be necessary for other plugins, so I also think that a solution like firing `InsertLeave` might be more appropriate.

For my part, I'm not experiencing this issue with nvim-cmp. The menu closes automatically when the cursor moves in insert mode.

Other possible solution would be revert the code to what it looked like before 8fc49ce841c34663b45f4fd4eb7c6b9b5df7704e. I will think about it.

**Comment by uga-rosa** [comment]
I was able to solve this by adding `do InsertLeave` to the jump mapping, but this should be set by the user with an understanding of the side effects.
```lua
M.next = function(idx)
    if snippy.can_jump(1) then
        vim.cmd('do InsertLeave')
        snippy.next()
    else
        feedkey(fallback[idx])
    end
end

M.previous = function(idx)
    if snippy.can_jump(-1) then
        vim.cmd('do InsertLeave')
        snippy.previous()
    else
        feedkey(fallback[idx])
    end
end
```
Close this PR.

**Comment by uga-rosa** [comment]
Oh, the cmp problem certainly doesn't happen. I don't know if I'm remembering it wrong or if it's a cmp update.

**Pull request closed without merging**
